### ISSUE TITLE
[Feature Request] Attributes

### ISSUE THREAD

**Issue by lonix1** [willdelphia/magicblock#4]
*Firstly, well done on creating this excellent plugin!*

Please allow for custom attributes. For example, when using bootstrap, we need to add `data-*`, `role`, `aria-*`, etc., attributes.

Ideal approach: have repeater control where we click "+" and add another attribute with key and value. This is the best way, but probably more difficult.

*Practical approach*: just have one more field, with a key-value string, e.g.
`data-customer='foo' role='document' aria-hidden='true'`

Then the plugin could split that string and add each key-value pair as an attribute.

**Comment by willdelphia** [comment]
You know, that's interesting. I actually a have a branch that allows the user to create `data-` attributes. I feel I could expand it to include `aria-` pretty easily. Maybe this weekend I'll have time to. Thanks for the request.

**Comment by lonix1** [comment]
That would be awesome and I'll be your first beta tester!

Keep in mind though that there are more use cases as well (e.g. `role`). But I guess you can't add another field every time someone thinks of a new use case - it would get messy and hard to maintain. So a more generic approach would be best long term.

BTW I'm amazed at how much easier it is to use the block editor, just because of this plugin.

**Comment by willdelphia** [comment]
Hi. So I pushed an updated version to the wordpress.org plugin directory. Let me know how you like it. 

Basically there is a section for any custom attribute key/value pair. 
<img width="423" alt="screenshot-2" src="https://user-images.githubusercontent.com/4534359/72688830-c9b65600-3ad0-11ea-9039-e50f0d41ee80.png">

**Comment by lonix1** [comment]
Awesome new feature, thanks!
